[package]
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]
name = "kmer-counter"
version = "0.1.0"

[dependencies]
clap = "2.19.0"
env_logger = "0.3.5"
error-chain = "0.7.1"
log = "0.3.6"
memchr = "0.1.11"
memmap = "0.5.0"
rayon = "0.5.0"
